apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: autolabel-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
  - watch
  - create
  - update
  - delete
